### ISSUE TITLE
setup playbook requires sudo privileges

### ISSUE THREAD

**Issue by micovery** [carlosfrias/apigee-opdk-playbook-setup-ansible#8]
When running the setup playbook, I was using an account that even though has sudo privilege, it requires password to be used. (as opposed tom passwordless sudo)

I got this error:

![image](https://user-images.githubusercontent.com/1885394/55587007-38abf500-56df-11e9-8a4a-8cfae2d6973c.png)

To make this work I had to tell ansible to prompt for the password whenever sudo privilege is nedeed.

e.g.

```
ansible-playbook setup.yml --ask-become-pass
```

**Comment by micovery** [comment]
Proposed fix to the docs: PR https://github.com/carlosfrias/apigee-opdk-playbook-setup-ansible/pull/9

**Comment by carlosfrias** [comment]
This task already escalate to sudo. This likely means that you don't have sudo privilege. This error is the prompt to re-invoke the task with the -K flag or --ask-become-pass.
